export const TOGGLE_NAV_DRAWER = 'TOGGLE_NAV_DRAWER';
export const INCREMENT_COUNTER = 'INCREMENT_COUNTER';
export const DECREMENT_COUNTER = 'DECREMENT_COUNTER';
export const RESET_ROWS = 'RESET_ROWS';
export const START_TASK = 'START_TASK';
export const LOADING = 'LOADING';

// Navigation
export const SET_PRODUCT = 'SET_PRODUCT';

// Home
export const GET_DASHBOARD_SUCCESSS = 'GET_DASHBOARD_SUCCESSS';
export const FILTER_BAR_CHART = 'FILTER_BAR_CHART';
export const GET_LANGUAGE_SUCCESS = 'GET_LANGUAGE_SUCCESS';
export const SET_LANGUAGE = 'SET_LANGUAGE';

// Account
export const LOAD_CONNECTION_SETTINGS_SUCCESS = 'LOAD_CONNECTION_SETTINGS_SUCCESS';
export const LOAD_FTP_FILE_LOG_SUCCESS = 'LOAD_FTP_FILE_LOG_SUCCESS';
export const LOAD_LAST_TRANSACTION_HISTORY_SEARCH_SUCCESS = 'LOAD_LAST_TRANSACTION_HISTORY_SEARCH_SUCESS';
export const LOAD_TRANSACTION_HISTORY = 'LOAD_TRANSACTION_HISTORY';
export const LOAD_TRANSACTION_HISTORY_SUCCESS = 'LOAD_TRANSACTION_HISTORY_SUCCESS';
export const LOAD_TRANSACTION_DETAILS_SUCCESS = 'LOAD_TRANSACTION_DETAILS_SUCCESS';
export const TRANSMITTING_TRANSACTION = 'TRANSMITTING_TRANSACTION';
export const TRANSMIT_ALL_SUCCESS = 'TRANSMIT_ALL_SUCCESS';
export const DELETE_TRANSACTION_SUCCESS = 'DELETE_TRANSACTION_SUCCESS';
export const SEND_TRANSACTION_SUCCESS = 'SEND_TRANSACTION_SUCCESS';
export const RESEND_TRANSACTION_SUCCESS = 'RESEND_TRANSACTION_SUCCESS';
export const UPDATE_CHECKBOXES = 'UPDATE_CHECKBOXES';

//  Calendar
export const SELECT_COMPANY = 'SELECT_COMPANY';
export const SELECT_COUNTRY = 'SELECT_COUNTRY';
export const OPEN_MODAL = 'OPEN_MODAL';
export const CLOSE_MODAL = 'CLOSE_MODAL';
export const CLOSE_EXPORT_CONTENT_MODAL = 'CLOSE_EXPORT_CONTENT_MODAL';
export const ADD_RETURN = 'ADD_RETURN';
export const REMOVE_RETURN = 'REMOVE_RETURN';
export const SELECT_FREQUENCY = 'SELECT_FREQUENCY';
export const CHECK_EFILE = 'CHECK_EFILE';
export const CHECK_VAT_GROUP = 'CHECK_VAT_GROUP';
export const CHANGE_FROM_DATE = 'CHANGE_FROM_DATE';
export const CHANGE_TO_DATE = 'CHANGE_TO_DATE';
export const LOAD_SETTINGS_SUCCESS = 'LOAD_SETTINGS_SUCCESS';
export const LOAD_RETURNS_SUCCESS = 'LOAD_RETURNS_SUCCESS';
export const LOAD_RETURNS = 'LOAD_RETURNS';
export const SELECT_ROW = 'SELECT_ROW';
export const SELECT_ROWS = 'SELECT_ROWS';

// Notification Log
export const LOAD_NOTIFICATION_LOG_SUCCESS = 'LOAD_NOTIFICATION_LOG_SUCCESS';
export const GET_INVOICES_NUMBERS_SUCCESS = 'GET_INVOICES_NUMBERS_SUCCESS';
export const EXPORT_SUMMARY_SUCCESS = 'EXPORT_SUMMARY_SUCCESS';

// API log
export const GET_API_LOGS_SUCCESS = 'GET_API_LOGS_SUCCESS';
export const GET_API_LOG_SUCCESS = 'GET_API_LOG_SUCCESS';

// Invoices
export const GET_INVOICES_SUCCESS = 'GET_INVOICES_SUCCESS';
export const GET_INVOICE_LINES_SUCCESS = 'GET_INVOICE_LINES_SUCCESS';
export const DELETE_INVOICES_SUCCESS = 'DELETE_INVOICES_SUCCESS';
export const FILTER_COLUMNS = 'FILTER_COLUMNS';
export const SET_COLUMNS = 'SET_COLUMNS';
export const SET_FORM = 'SET_FORM';
export const LOADING_DETAILS = 'LOADING_DETAILS';
export const BEGIN_EXECUTE_INVOICE_ACTION = 'BEGIN_EXECUTE_INVOICE_ACTION';
export const EXECUTE_INVOICE_ACTION_SUCCESS = 'EXECUTE_INVOICE_ACTION_SUCCESS';


// Invoice monitor
export const GET_INVOICE_DETAILS_SUCCESS = 'GET_INVOICE_DETAILS_SUCCESS';
export const GET_INVOICES_MONITOR_SUCCESS = 'GET_INVOICES_MONITOR_SUCCESS';

// Return Calculator
export const GET_FILING_CALCULATOR_DATA_SUCCESSS = 'GET_FILING_CALCULATOR_DATA_SUCCESSS';
export const CALCULATE_RETURN_SUCCESS = 'CALCULATE_RETURN_SUCCESS';
export const EXPORT_CALCULATED_FILING_ERRORS = 'EXPORT_CALCULATED_FILING_ERRORS';
export const DOWNLOAD_CALCULATED_FILE_SUCCESS = 'DOWNLOAD_CALCULATED_FILE_SUCCESS';
export const CLEAN_CALCULATED_EXPORT_ERRORS = 'CLEAN_CALCULATED_EXPORT_ERRORS';

// Calendar http
export const LOAD_AVAILABLE_RETURNS_SUCCESS = 'LOAD_AVAILABLE_RETURNS_SUCCESS';
export const SAVE_PREFERENCE_ERROR = 'SAVE_PREFERENCE_ERROR';
export const SAVE_PREFERENCE_SUCCESS = 'SAVE_PREFERENCE_SUCCESS';

export const LOAD_REPORTS = 'LOAD_REPORTS';
export const LOAD_REPORTS_SUCCESS = 'LOAD_REPORTS_SUCCESS';
export const LOAD_FREQUENCIES_SUCCESS = 'LOAD_FREQUENCIES_SUCCESS';

// Filing workflow
export const ADJUST_STEP_RANK = 'ADJUST_STEP_RANK';
export const SAVE_WORKFLOW = 'SAVE_WORKFLOW';
export const LOAD_WORKFLOW_SUCCESS = 'LOAD_WORKFLOW_SUCCESS';
export const SAVE_WORKFLOW_SUCCESS = 'SAVE_WORKFLOW_SUCCESS';
export const SAVE_WORKFLOW_ERROR = 'SAVE_WORKFLOW_ERROR';
export const UPDATE_STEPS_ORDER = 'UPDATE_STEPS_ORDER';
export const ADD_STEP = 'ADD_STEP';
export const DELETE_STEP = 'DELETE_STEP';
export const TOGGLE_CARD = 'TOGGLE_CARD';
export const MOVE_UP = 'MOVE_UP';
export const MOVE_DOWN = 'MOVE_DOWN';
export const CHANGE_STEP_NAME = 'CHANGE_STEP_NAME';
export const CHANGE_STEP_CHECKBOX = 'CHANGE_STEP_CHECKBOX';
export const CHANGE_STEP_DAYS = 'CHANGE_STEP_DAYS';
export const CHANGE_DEFAULT_ASSIGNEE = 'CHANGE_DEFAULT_ASSIGNEE';
export const GENERATE_RETURN_SUCCESS = 'GENERATE_RETURN_SUCCESS';
export const SAVE_EDIT_REPORT_SUCCESS = 'SAVE_EDIT_REPORT_SUCCESS';

// Filing dashboard
export const TOGGLE_VIEW = 'TOGGLE_VIEW';
export const UPDATE_CARD_LANE = 'UPDATE_CARD_LANE';
export const SET_FILTER = 'SET_FILTER';
export const SET_PERIOD = 'SET_PERIOD';
export const SAVE_DASHBOARD = 'SAVE_DASHBOARD';
export const LOAD_DASHBOARD = 'LOAD_DASHBOARD';
export const SAVE_DASHBOARD_SUCCESS = 'SAVE_DASHBOARD_SUCCESS';
export const LOAD_DASHBOARD_SUCCESS = 'LOAD_DASHBOARD_SUCCESS';
export const OPEN_MONTH = 'OPEN_MONTH';
export const OPEN_MONTH_SUCCESS = 'OPEN_MONTH_SUCESS';
export const CLOSE_MONTH_SUCCESS = 'CLOSE_MONTH_SUCCESS';

// Filing details
export const LOAD_DETAILS_SUCCESS = 'LOAD_DETAILS_SUCCESS';
export const SAVE_COMMENTS_SUCCESS = 'SAVE_COMMENTS_SUCCESS';
export const UPDATE_STATUS = 'UPDATE_STATUS';
export const UPDATE_STATUS_SUCCESS = 'UPDATE_STATUS_SUCCESS';
export const UPDATE_ASIGNEE = 'UPDATE_ASIGNEE';
export const UPDATE_ASIGNEE_SUCCESS = 'UPDATE_ASIGNEE_SUCCESS';
export const ADD_FOLLOWER_SUCCESS = 'ADD_FOLLOWER_SUCCESS';
export const DOWNLOAD_TRANSMISSION_FILE = 'DOWNLOAD_TRANSMISSION_FILE';
export const DOWNLOAD_TRANSMISSION_FILE_SUCCESS = 'DOWNLOAD_TRANSMISSION_FILE_SUCCESS';
export const TRANSMISSION_REPORT = 'TRANSMISSION_REPORT';
export const TRANSMISSION_REPORT_SUCCESS = 'TRANSMISSION_REPORT_SUCCESS';
export const UPDATE_REPORT_VERSION_NAME_SUCCESS = 'UPDATE_REPORT_VERSION_NAME_SUCCESS';
export const RESTORE_VERSION_SUCCESS = 'RESTORE_VERSION_SUCCESS';
export const EXPORT_FILING_SUCCESS = 'EXPORT_FILING_SUCCESS';
export const EXPORT_FILING_ERRORS = 'EXPORT_FILING_ERRORS';
export const UPDATE_SELECTED_VENDORS = 'UPDATE_SELECTED_VENDORS';
export const EDIT_DRILL_DOWN_CELL = 'EDIT_DRILL_DOWN_CELL';
export const SAVE_REPORT_FILE_SUCCESS = 'SAVE_REPORT_FILE_SUCCESS';

// Users
export const LOAD_AVAILABLE_USERS_SUCCESS = 'LOAD_AVAILABLE_USERS_SUCCESS';
export const LOAD_NOTIFICATION_PREFERENCES_SUCCESS = 'LOAD_NOTIFICATION_PREFERENCES_SUCCESS';
export const SELECT_NOTIFICATION_PREFERENCES = 'SELECT_NOTIFICATION_PREFERENCES';

// Reports
export const GET_OTHERLISTING_REPORTS_SUCCESS = 'GET_OTHERLISTING_REPORTS_SUCCESS';
export const GET_AVAILABLE_COMPANIES_SUCCESS = 'GET_AVAILABLE_COMPANIES_SUCCESS';
export const GENERATE_REPORT_SUCCESS = 'GENERATE_REPORT_SUCCESS';
export const PROGRAM_REPORT_SUCCESS = 'PROGRAM_REPORT_SUCCESS';

// Export data
export const GET_EXPORT_PAGE_INFO = 'GET_EXPORT_PAGE_INFO';
export const EXPORT_DATA_SUCCESS = 'EXPORT_DATA_SUCCESS';
export const GET_COUNTRIES_SUCCESS = 'GET_COUNTRIES_SUCCESS';

//  Ajax status
export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';
export const DISMISS_TOAST = 'DISMISS_TOAST';
export const AJAX_CALL_SUCCESS = 'AJAX_CALL_SUCCESS';

// Invoice Dashboard
export const GET_INVOICE_DASHBOARD_SUCCESS = 'GET_INVOICE_DASHBOARD_SUCCESS';
export const GET_LAST_REJECTED_SUCCESS = 'GET_LAST_REJECTED_SUCCESS';
export const GET_SERVER_STATUS_SUCCESS = 'GET_SERVER_STATUS_SUCCESS';
export const GET_SUGGESTIONS_SUCCESS = 'GET_SUGGESTIONS_SUCCESS';
export const CLEAR_LIST = 'CLEAR_LIST';

// Configuration
export const SAVE_CONFIGURATION_SUCCESS = 'SAVE_CONFIGURATION_SUCCESS';
export const LOAD_CONFIGURATION_SUCCESS = 'LOAD_CONFIGURATION_SUCCESS';
export const GET_ALL_COMPANIES_SUCCESS = 'GET_ALL_COMPANIES_SUCCESS';

// Establishments
export const SAVE_ESTABLISHMENTS_SUCCESS = 'SAVE_ESTABLISHMENTS_SUCCESS';
export const LOAD_ESTABLISHMENTS = 'LOAD_ESTABLISHMENTS';
export const LOAD_ESTABLISHMENTS_SUCCESS = 'LOAD_ESTABLISHMENTS_SUCCESS';
export const GET_ESTABLISHMENT_SUCCESS = 'GET_ESTABLISHMENT_SUCCESS';
export const START_CANCEL_EVENT_SUCCESS = 'START_CANCEL_EVENT_SUCCESS';
export const CANCEL_EVENT_SUCCESS = 'CANCEL_EVENT_SUCCESS';
export const CANCEL_TRANSMISSION = 'CANCEL_TRANSMISSION';

// Capital Assets
export const SAVE_CAPITAL_ASSETS_SUCCESS = 'SAVE_CAPITAL_ASSETS_SUCCESS';
export const LOAD_CAPITAL_ASSETS = 'LOAD_CAPITAL_ASSETS';
export const LOAD_CAPITAL_ASSETS_SUCCESS = 'LOAD_CAPITAL_ASSETS_SUCCESS';
export const GET_CAPITAL_ASSET_SUCCESS = 'GET_CAPITAL_ASSET_SUCCESS';
export const GET_CANDIDATE_BATCHES_SUCCESS = 'GET_CANDIDATE_BATCHES_SUCCESS';
export const CHANGE_TAB = 'CHANGE_TAB';
export const LOADING_CAPITAL_ASSETS = 'LOADING_CAPITAL_ASSETS';
export const GET_CANDIDATE_ASSETIDS_SUCCESS = 'GET_CANDIDATE_ASSETIDS_SUCCESS';
