// Home
export const LOADING = 'LOADING';
export const QUERY_CONSULTA_FORM_SUCCESS = 'QUERY_CONSULTA_FORM_SUCCESS';

//  Ajax status
export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';
export const DISMISS_TOAST = 'DISMISS_TOAST';
export const AJAX_CALL_SUCCESS = 'AJAX_CALL_SUCCESS';
