export default {
  home: 'home',
  layout: 'layout',
  counter: 'counter',
  calendar: 'calendar',
  ajaxCalls: 'ajaxCalls',
  filingWorkflow: 'filingWorkflow',
  filingDashboard: 'filingDashboard',
  form: 'form',
  filingDetails: 'filingDetails',
  users: 'users',
  accounts: 'accounts',
  transactions: 'transactions',
  notificationLog: 'notificationLog',
  apiLog: 'apiLog',
  reports: 'reports',
  exportData: 'exportData',
  establishments: 'establishments',
  capitalAssets: 'capitalAssets',
  eventDashboard: 'eventDashboard',
  invoices: 'invoices',
  invoiceMonitor: 'invoiceMonitor',
  invoiceDashboard: 'invoiceDashboard',
  configuration: 'configuration',
  navigation: 'navigation'
};
